# $Id: Makefile.cc2420,v 1.00 2018/03/27 17:08:42 vinicius Exp $

IOTUS_RADIO_DRIVER_NAME = cc2420

# If more folders need to be compiled, just add them to the following line, like
THIS_SUB_MODULES := $(THIS_MODULE_FOLDER)/../../framers/radio-framer-802154 \
$(THIS_MODULE_FOLDER)/../../framers/generic-frame802154