/**
 * \defgroup decription...
 *
 * This...
 *
 * @{
 */

/*
 * packet-default-additional-info.h
 *
 *  Created on: Nov 15, 2017
 *      Author: vinicius
 */

#ifndef IOTUS_ARCH_SERVICES_PACKET_DEFAULT_ADDITIONAL_INFO_H_
#define IOTUS_ARCH_SERVICES_PACKET_DEFAULT_ADDITIONAL_INFO_H_

//The field infoPiece can have more valuer then these, but these are the standard
enum IOTUS_MSG_PIECE_INFO_TYPE {
  IOTUS_MSG_PIECE_INFO_TYPE_INITIAL_SOURCE_ADDRESS = 0,
  IOTUS_MSG_PIECE_INFO_TYPE_PREV_SOURCE_ADDRESS,
  IOTUS_MSG_PIECE_INFO_TYPE_FINAL_DEST_ADDRESS,
  IOTUS_MSG_PIECE_INFO_TYPE_SEQUENCE_NUMBER,


  IOTUS_MSG_PIECE_INFO_TYPE___N,
};

/* Application layer has twice the range, so that it can include sub-layers of protocols */
#define IOTUS_MSG_PIECE_INFO_TYPE_RANGE_PER_LAYER     ((256-IOTUS_MSG_PIECE_INFO_TYPE___N)/5)
#define IOTUS_MSG_PIECE_INFO_DATA_LINK_TYPES_BEGIN     (IOTUS_MSG_PIECE_INFO_TYPE___N)
#define IOTUS_MSG_PIECE_INFO_ROUTING_TYPES_BEGIN       (IOTUS_MSG_PIECE_INFO_TYPE_RANGE_PER_LAYER+IOTUS_MSG_PIECE_INFO_DATA_LINK_TYPES_BEGIN)
#define IOTUS_MSG_PIECE_INFO_TRANSPORT_TYPES_BEGIN     (IOTUS_MSG_PIECE_INFO_TYPE_RANGE_PER_LAYER+IOTUS_MSG_PIECE_INFO_ROUTING_TYPES_BEGIN)
#define IOTUS_MSG_PIECE_INFO_APPLICATION_TYPES_BEGIN   (IOTUS_MSG_PIECE_INFO_TYPE_RANGE_PER_LAYER+IOTUS_MSG_PIECE_INFO_TRANSPORT_TYPES_BEGIN)


#endif /* IOTUS_ARCH_SERVICES_PACKET_DEFAULT_ADDITIONAL_INFO_H_*/

/* The following stuff ends the \defgroup block at the beginning of
   the file: */

/** @} */
